# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: n370.info
email: ama@n370.info
description: > # this means to ignore newlines until "baseurl:"
  Trouble maker, problem solver.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://n370.info" # the base hostname & protocol for your site
twitter_username: n370n370
github_username:  n370

# Build settings
markdown: kramdown
gems: [bourbon, neat]
